VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = no
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
VIALRGB_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
